/// ------------------------------------- ///
/// Automatically generated. DO NOT EDIT. ///
/// ------------------------------------- ///

/// <reference path="../src/declarations/angular/angular.d.ts" />
/// <reference path="../src/declarations/commonjs.d.ts" />
/// <reference path="../src/declarations/jquery/jquery.d.ts" />
/// <reference path="../src/declarations/mocks/angular-mocks.d.ts" />
/// <reference path="../src/declarations/mocks/jasmine.d.ts" />
/// <reference path="../src/declarations/mocks/karma-jasmine.d.ts" />
/// <reference path="../src/declarations/mocks/selenium-webdriver.d.ts" />
/// <reference path="../src/model/cards/cards.d.ts" />
/// <reference path="../src/model/gameplay/gameplay.d.ts" />
/// <reference path="../src/model/gameplay/promise-matchers.d.ts" />
/// <reference path="../src/model/model.d.ts" />
/// <reference path="../src/model/players/players.d.ts" />

// Generated by dts-bundle

declare module 'tower' {
    export var Module: ng.IModule;
    
}

